print("what is your name: ")
name=int(input())
print("the length of the name is: ")
a=input()
len(name)
print("enter your age: ")
age=int(input())
print("your age is",age)
print("your age will be",age+1,"in next year")
